### ISSUE TITLE
GUI Error on my Windows10

### ISSUE THREAD

**Issue by admin-kepo** [polygontwist/splinewriter#6]
![image](https://user-images.githubusercontent.com/19965963/80298157-93fdc900-87b3-11ea-80cb-4a89cff4ccd5.png)
i dont know why this is happened on my windows10,
i have tried install and try install again but the result not change. 
Please Help !!

**Comment by polygontwist** [comment]
please try to delete the file options.json Path is shown in the screenshot. When the program restarts it should be recreated correctly. Otherwise please post the content of the file "optionen.json" here.

**Comment by polygontwist** [comment]
or rename the file. perhaps it complies with the machine settings " too much?

**Comment by admin-kepo** [comment]
Great. It's works now. thanks
